server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://Wellora:Pvx5QzgPPm3PVtq5@cluster0.dfxd3lp.mongodb.net/wellora?retryWrites=true&w=majority&appName=Cluster0}
  application:
    name: wellora-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET:wellora-secret-key-2024}
  expiration: ${JWT_EXPIRATION:86400}

logging:
  level:
    br.com.fiap.wellora: ${LOG_LEVEL:DEBUG}
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
