server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/wellora}
  application:
    name: wellora-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForDevelopmentOnlyNotForProduction123456789}
  expiration: ${JWT_EXPIRATION:86400}
  anonymous:
    secret: ${JWT_ANONYMOUS_SECRET:myAnonymousSecretKeyForDevelopmentOnly123456789}
    expiration: ${JWT_ANONYMOUS_EXPIRATION:3600}

logging:
  level:
    '[br.com.fiap.wellora]': ${LOG_LEVEL:INFO}
    '[org.springframework.security]': WARN
    '[com.mongodb]': WARN
    '[org.mongodb.driver]': WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
